# Generated by Django 4.1.3 on 2022-11-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='content',
        ),
    ]
